import 'package:hive/hive.dart';
import 'package:smart_save/features/home/domain/entities/product_hive_model.dart';

import 'customer_hive_model.dart';

part 'cart_hive_model.g.dart'; // This file will be generated by the build runner

@HiveType(typeId: 2) // Specifies the Hive type ID for the Product class
class CartHiveModel extends HiveObject {
  @HiveField(0)
  final CustomerHiveModel customer;

  @HiveField(1)
  final List<ProductHiveModel> cartList;

  @HiveField(2)
  final int totalPrice;

  CartHiveModel({
    required this.customer,
    required this.cartList,
    required this.totalPrice,
  });
}
